name: Hello World

author: Filip Jasic
description: bla
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: Filip
outputs:
  time:
    description: 'greeting time'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}