name: Custom actions

on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: naslov
          body: telo
          assignees: 'fjasic'
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'jasar'
      - run: |
          echo "Time ${{ steps.hello.outputs.time }}"
          echo $HELLO